image: Visual Studio 2022

install:
  - SET JAVA_HOME=C:\Program Files\Java\jdk17
  - SET PATH=%JAVA_HOME%\bin;%PATH%

build_script:
  - cmd: >-
      build.cmd update-build-version sonar test nuget-pack --configuration Release

test: off

cache:
  - tools
  - '%USERPROFILE%\.sonar\cache'

artifacts:
  - path: 'artifacts\*.nupkg'
